name: pokedex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  http: ^0.13.1
  sqflite: ^2.0.0+3
  dropdown_button2: ^2.3.8
  flutter_staggered_grid_view: ^0.7.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
# To add assets to your application, add an assets section, like this:
  assets:
    - images/
